version: "2"

services:
  openhab:
    image: openhab/openhab:2.1.0-amd64
    restart: always
    volumes:
      - ./openhab/conf:/openhab/conf
      - ./openhab/userdata:/openhab/userdata
      - ./openhab/addons:/openhab/addons
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - 9080:8080
    devices:
      - /dev/ttyUSB0

  mqtt:
    image: eclipse-mosquitto
    restart: always
    ports:
      - 1883:1883

  influxdb:
    image: influxdb
    restart: always
    volumes:
      - /srv/openhab/influxdb:/var/lib/influxdb
    ports:
      - 8086:8086
  
  grafana:
    image: grafana/grafana
    restart: always
    volumes:
      - /srv/openhab/grafana:/var/lib/grafana
    ports:
      - 3000:3000

